name: user_repository
description: The repository that handles User

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #localization
  intl: ^0.18.1

  # firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.0
  # firebase web
  # firebase_core_web: ^2.16.0
  # firebase_auth_web: ^5.11.4

  equatable: ^2.0.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
