name: procrastinator
description: 'Application for managing attendance.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: any
  flutter_localizations:
    sdk: flutter

  ## Repositories

  user_repository:
    path: packages/user_repository

  group_repository:
    path: packages/group_repository

  cupertino_icons: ^1.0.6

  ## Assets
  spider: ^4.2.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0

  ## Localization
  # intl: ^0.18.1

  ## Local storage
  shared_preferences: ^2.3.0
  # flutter_secure_storage: ^4.2.1

  ## Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0

  ## Auth
  # email_validator: ^2.1.17
  # sign_in_with_apple: ^6.1.0

  ## State
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5

  ## Utils
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.14.0
  uuid: ^4.4.0
  json_annotation: ^4.8.1
  clock: ^1.1.1
  package_info_plus: ^8.1.0

  ## Logging
  stack_trace: ^1.11.1
  sentry_flutter: ^8.7.0

  ## Widgets
  table_calendar: ^3.0.9
  modal_bottom_sheet: ^3.0.0
  # percent_indicator: ^4.2.3
  # calendar_date_picker2: ^0.5.5

  ## UI
  # flutter_animated_icons: ^1.0.1
  animated_icon: ^0.0.9
  rive_animated_icon: ^2.0.0
  lottie: ^3.1.2
  cached_network_image: ^3.4.0

  ## Device
  geolocator: ^12.0.0

  intl: ^0.19.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  ## Testing
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

  ## Utils
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.4.1
  freezed: ^2.5.7

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/Procra2000Splash.png

flutter:
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true
  class_name: Localization
  arb_dir: lib/src/core/constant/localization/l10n
  output_dir: lib/src/core/constant/localization/generated
