name: procrastinator
description: 'Application for managing attendance.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #REPOSITORIES
  user_repository:
    path: packages/user_repository

  entry_repository:
    path: packages/entry_repository

  lection_repository:
    path: packages/lection_repository

  geolocation_repository:
    path: packages/geolocation_repository

  form_validation:
    path: packages/form_validation

  cupertino_icons: ^1.0.6

  #assets
  spider: ^4.2.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0

  #localization
  # intl: ^0.18.1

  # local storage
  # hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1

  # isar_flutter_libs: ^4.0.0-dev.13
  # path_provider: ^2.1.0
  # firebase
  firebase_core: ^2.30.0
  # firebase_auth: ^4.19.5
  # cloud_firestore: ^4.17.0
  # firebase web
  # firebase_core_web: ^2.16.0
  # firebase_auth_web: ^5.11.4
  # auth
  # email_validator: ^2.1.17
  # sign_in_with_apple: ^6.1.0
  # di
  get_it: ^7.7.0

  # state
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  # provider: ^6.1.2
  equatable: ^2.0.5

  # Utils
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  uuid: ^4.4.0
  # formz: ^0.7.0
  # flow_builder: ^0.1.0
  # geopositon
  # geolocator: ^12.0.0
  # api
  json_annotation: ^4.8.1
  clock: ^1.1.1

  # Logging
  stack_trace: ^1.11.1
  sentry_flutter: ^8.7.0

  # widgets
  table_calendar: ^3.0.9
  modal_bottom_sheet: ^3.0.0
  # percent_indicator: ^4.2.3
  # calendar_date_picker2: ^0.5.5
  #ui
  # flutter_animated_icons: ^1.0.1
  animated_icon: ^0.0.9
  rive_animated_icon: ^2.0.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/Procra2000Splash.png

flutter:
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true
  class_name: Localization
  arb_dir: lib/src/core/constant/localization/l10n
  output_dir: lib/src/core/constant/localization/generated
